stages: [train]

train_golden_path:
  stage: train
  variables:
    MLOPS_NETWORK: "mlops"
    PUBLIC_FQDN: "mlops-nginx"
    MLFLOW_BASE_PATH: "mlflow"
    TRAIN_CONFIG: "configs/ci.yaml"
  script:
    - make runner-build
    - make pull
    - make load-docker
    - make split-docker
    - make train-docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
