#mlflow
tracking_uri: "http://${PUBLIC_FQDN}/${MLFLOW_BASE_PATH}"
experiment_name: "mlops-examples/t92"
registered_model_name: "MLOpsExamples_T92_CV"
pipeline: "mlops-examples"

# data
data_dir: "/home/trevi/projects/msds_practicum/msds_practicum/data/raw"
real_test_dir: "/home/trevi/projects/msds_practicum/msds_practicum/data/real_test"
snapshots_dir: "artifacts/snapshots"

# Training
batch_size: 32
epochs: 200
learning_rate: .0001
weight_decay: .0001
patience: 15
seed: 42

# Data
image_size: [224, 224]
train_split: 0.7
val_split: 0.2
test_split: 0.1

# Model
backbone: 'densenet121'
pretrained: True
use_zenith_input: True

# Augmentation
use_mirroring: True
blur_prob: 0.5
blur_kernel_range: [3, 9]
noise_prob: 0.3
noise_std_range: [0.01, 0.05]
grayscale_prob: 0.5

# Real image monitoring
real_zenith_estimate: 30  # Estimate for your real photos
snapshot_every_n_epochs: 1  # Save snapshot every N epochs

# Feature Store
feast_repo: "feature_repo"
offline_store_uri: "postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/feast"